### ISSUE TITLE
icons

### ISSUE THREAD

**Issue by sam43434** [mathewcallaghan/australian-tv-network-logo-icons#1]
Hi, is it possible for new icons to be made for other regions besides newcastle? 

am after 

https://www.yourtv.com.au/guide/spencer-gulf/

and 

http://sattvguide.com.au/

in white 

thanks for reading

**Comment by mathewcallaghan** [comment]
Hi, Sorry slow reply I did not have notifications turned on so did not know this was here until now. It would be great to cover all areas I think. I will try and add more when I can. Are you using Tvheadend?

**Comment by sam43434** [comment]
Hi, yeah using tvheadend,  using your icons for personal use on my system which looks nice, But im missing alot since ive got Vast WA & Vast Vic as well as Dvb-T using spencer gulf area

**Comment by mathewcallaghan** [comment]
Thanks. If you go to **http://IP:9981/playlist** using the IP address of media center or computer it should download a M3U of the channels. I can use this to pair the icons with the channels, so they show up automatically.

**Comment by sam43434** [comment]
have uploaded it below
https://gofile.io/?c=wV5ay8

**Comment by mathewcallaghan** [comment]
Great, thanks. I will update the icons soon.

**Comment by mathewcallaghan** [comment]
I have added a lot of new icons, they should cover a lot more areas.

**Comment by sam43434** [comment]
Legend, looks much nicer now
https://imgur.com/Ju7bE76

**Comment by mathewcallaghan** [comment]
Thanks for the screenshot, looks good. I will close this issue now.
