### ISSUE TITLE
ABC Renamed/Re-Logo'd Channels

### ISSUE THREAD

**Issue by czuio** [mathewcallaghan/australian-tv-network-logo-icons#10]
Hey, Tried commenting on your website but I'm getting a Nonce Error (CloudFlare Caching? breaking the validation on the form from a quick google)

But 

ABC Kids/TV Plus -> ABC Family
ABC ME -> ABC Entertains

**Comment by czuio** [comment]
I've attached the SVG Logos I found from a quick Google.

![ABC_Family_Australia_logo_2024 svg](https://github.com/mathewcallaghan/australian-tv-network-logo-icons/assets/3814541/d0e56131-ff97-404e-aa4d-366ce59092f4)

![ABC_Entertains_logo svg](https://github.com/mathewcallaghan/australian-tv-network-logo-icons/assets/3814541/eac0b23e-9ce4-40c3-a22d-dd7340716382)

**Comment by mathewcallaghan** [comment]
Thanks @czuio I will update the icons shortly. The issue at Pure Services should be resolved now. I appreciate the updates.
