### ISSUE TITLE
Channel 9 name changes in Sydney and Melbourne, and new stations

### ISSUE THREAD

**Issue by Ozies** [mathewcallaghan/australian-tv-network-logo-icons#11]
Hi Matthew,

Channel 9 have changed their names to Channel 9 Melbourne & Channel 9 Sydney, and possibly other major cities as well.
There's also a 9Go!HD Melbourne and 9Go!HD Sydney, and possibly other major cities as well.

A new station called you.tv (link: https://youtv.com.au/)

And finally SBS South Asian Radio (link: https://www.sbs.com.au/audio/radio/south-asian)

Thanks for the great work keeping this repo going!

**Comment by mathewcallaghan** [comment]
Hi @Ozies Thanks for the updates. I have added the new icons and changed some names. Thank you.

**Comment by Ozies** [comment]
Thanks Matthew, that worked well!

I just noticed 2 more name changes:

10Bold is now 10 Bold Drama, 10Peach is now 10 Peach Comedy

**Comment by mathewcallaghan** [comment]
Thanks @Ozies Are these channels showing up like this in your area? In Newcastle they are still 10Bold and 10Peach.

**Comment by Ozies** [comment]
Yeah, in both Melbourne and Sydney they are now.

**Comment by mathewcallaghan** [comment]
Okay thank you @Ozies. I see now that they have updated the logos but the broadcast channel name remains the same. I have updated both 10 icons.

**Comment by Ozies** [comment]
Thanks Matthew, that has fixed it for me.

I noticed the broadcast name change in Sydney when I set up a TVHeadend server for a mate there, so I then checked mine here in Melbourne, and the broadcast names have changed here as well.
