### ISSUE TITLE
Icon request for Victoria

### ISSUE THREAD

**Issue by DannMendis** [mathewcallaghan/australian-tv-network-logo-icons#3]
Awesome repo and love it.

Can I please request below as they are missing...
 - SpreeTV
 - openshop
 - C31

**Comment by mathewcallaghan** [comment]
Thanks for that @DannMendis 
I have added new icons, spree tv, open shop and c31 melbourne.

**Comment by DannMendis** [comment]
Much appreciated @mathewcallaghan. These icons look awesome in my Kodi boxes. Thanks for this fantastic icons.
