### ISSUE TITLE
Canberra Missing Icons

### ISSUE THREAD

**Issue by CV8R** [mathewcallaghan/australian-tv-network-logo-icons#5]
Just found your work!  Thank you Mathew, what a fantastic resource!

Quick note to let you know that 2 channel icons are missing for Canberra

ch9 canberra
7hd canberra

Cheers.
CV8R

**Comment by mathewcallaghan** [comment]
Thanks @CV8R 
The icons have been updated.

**Comment by CV8R** [comment]
Was sitting in front of the TV watching the cricket. I can confirm they are now appearing.

I don't know how I missed it earlier but 7 canberra appears to be missing too.

7 canberra

Cheers!

**Comment by mathewcallaghan** [comment]
That's great @CV8R I have made the changes for Seven Canberra also.

Thanks

**Comment by CV8R** [comment]
Cheers! Sorted. Having them download direct from Github is genius.

**Comment by CV8R** [comment]
Sorry to be that guy..  I thought i would log onto my parents place on the NSW Sth Coast and chane theirs over.  I found the following were missing if you would be so kind as to add them.

10 south coast
7 sth coast
Ch9 wollongong
10 hd south coast
7hd sth coast
7two sth coast
7mate sth coast
7matehd sth coast
9hd south coast
9hd wollongong

Not sure if you wanted a new issue for this or not.

**Comment by mathewcallaghan** [comment]
No worries, I have made the changes. Some of these icons exist but the station changes the name, deciding to change it from sth to south etc. Name based matching is not a perfect way to do it but it is reliable in my experience. 

Thanks
