### ISSUE TITLE
Adelaide channel 44

### ISSUE THREAD

**Issue by mattaltus** [mathewcallaghan/australian-tv-network-logo-icons#6]
Hi,

This one would be handly to grab.

https://www.c44.au/wp-content/uploads/2022/09/cropped-logo_44_cropped.png

Thanks

**Comment by mattaltus** [comment]
comes through tvheadend as 'adelaide/564.5MHz/44 Adelaide'

**Comment by mathewcallaghan** [comment]
Hi @mattaltus

Thanks for that. I have added an icon "44 adelaide"
