### ISSUE TITLE
Add icon for Nickelodeon and rename C31 Melbourne to C31

### ISSUE THREAD

**Issue by zan73** [mathewcallaghan/australian-tv-network-logo-icons#9]
Hi Matt, can you add a new colour icon for Nickelodeon (named nickelodeon.png) and also rename c31 melbourne.png to c31.png to align with tvheadend?

**Comment by mathewcallaghan** [comment]
Hi, thank you. I have added a icon for Nickelodeon and changed c31.

Thanks.

**Comment by zan73** [comment]
Thanks very much for the quick turnaround.
I just noticed that SBS have added NITV HD, would you be able to create "nitv hd.png" as well?

**Comment by mathewcallaghan** [comment]
Thanks again @zan73 The NITV HD icon is there, I also noticed that the logo has been updated to a new design. The icons now use this design.
